name: Blue-Green Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        clean: false  # Отключает очистку рабочей директории

    - name: Initialize current version
      run: |
        if [ ! -f current_version ]; then
          echo "blue" > current_version
        fi

    - name: Debug file paths
      run: |
        ls -l
        ls -l blue/
        ls -l green/

    - name: Debug green folder
      run: |
        WORKSPACE=${{ github.workspace }}
        echo "Contents of green folder:"
        ls -l ${WORKSPACE}/green || echo "Green folder is not accessible"

    - name: Set deployment target
      id: set-target
      run: |
        CURRENT=$(cat current_version)
        if [ "$CURRENT" = "blue" ]; then
          echo "NEW_VERSION=green" >> $GITHUB_ENV
        else
          echo "NEW_VERSION=blue" >> $GITHUB_ENV
        fi
        echo "Current version: $CURRENT"
        echo "New version: ${{ env.NEW_VERSION }}"

    - name: Deploy new version
      run: |
        NEW_VERSION=${{ env.NEW_VERSION }}
        WORKSPACE=${{ github.workspace }}

        cd ${WORKSPACE}

        if [ -d "${NEW_VERSION}" ]; then
          echo "Directory ${NEW_VERSION} exists."
          ls -l ${NEW_VERSION}
        else
          echo "Directory ${NEW_VERSION} does not exist or is inaccessible."
          exit 1
        fi

        rm -rf ./*
        cp -r ${WORKSPACE}/${NEW_VERSION}/* ${WORKSPACE}/
        echo $NEW_VERSION > current_version

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./

