name: Blue-Green Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        clean: false

    - name: Initialize current version
      run: |
        if [ ! -f current_version ]; then
          echo "blue" > current_version
        fi

    - name: Set deployment target
      id: set-target
      run: |
        echo "Reading current version..."
        if [ -f current_version ]; then
          CURRENT=$(cat current_version)
        else
          echo "current_version file not found! Defaulting to 'blue'."
          CURRENT="blue"
        fi
        echo "Current version: $CURRENT"

        # Определяем новую версию
        if [ "$CURRENT" = "blue" ]; then
          NEW_VERSION="green"
        else
          NEW_VERSION="blue"
        fi

        echo "New version: $NEW_VERSION"

        # Сохраняем переменные в GITHUB_ENV
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
        echo "CURRENT=$CURRENT" >> $GITHUB_ENV

    - name: Deploy new version
      run: |
        NEW_VERSION=${{ env.NEW_VERSION }}
        WORKSPACE=${{ github.workspace }}

        echo "Deploying new version: $NEW_VERSION"
        cd ${WORKSPACE}

        # Проверяем, что файл index.html в папке существует
        if [ -f "${WORKSPACE}/${NEW_VERSION}/index.html" ]; then
          echo "File index.html exists in ${NEW_VERSION}."
          ls -l ${WORKSPACE}/${NEW_VERSION}/index.html
        else
          echo "File index.html does not exist in ${NEW_VERSION}!"
          exit 1
        fi

        # Удаляем старый index.html из корня
        echo "Removing old index.html from root..."
        rm -f ${WORKSPACE}/index.html

        # Копируем index.html из новой версии в корень
        echo "Copying new index.html to root..."
        cp ${WORKSPACE}/${NEW_VERSION}/index.html ${WORKSPACE}/index.html

        # Проверяем содержимое корня
        echo "Contents of root after copying:"
        ls -l ${WORKSPACE}/index.html

        # Обновляем файл current_version
        echo "Updating current_version to $NEW_VERSION..."
        echo $NEW_VERSION > ${WORKSPACE}/current_version
        cat ${WORKSPACE}/current_version

    - name: Save and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # Добавляем изменения и принудительно пушим
        git add .
        git commit -m "Update current_version to ${{ env.NEW_VERSION }}" || echo "Nothing to commit"
        git pull --rebase origin main || echo "Nothing to rebase"
        git push origin main --force  # Принудительный пуш

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        force_orphan: true 
